name: Omnix build-push-package

on:
  create:
    tags:
      - "v*"

env:
  GHA_TOKEN: ${{secrets.GHA_TOKEN}}

jobs:
  docker:
    if: |
      github.event_name == 'pull_request' || 
      github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v')
    name: Build and Push
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@omnix-ia'

      - name: Auth with Github Registry 
        run: |
          echo -e "@omnix-ia:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=\${GHA_TOKEN}\nalways-auth=true" > .npmrc

      - name: Cache Node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}